# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lenovo\Desktop\Python\Programlar\Todo App\sign_in.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_sign_in(object):
    def setupUi(self, sign_in):
        sign_in.setObjectName("sign_in")
        sign_in.resize(390, 404)
        sign_in.setMinimumSize(QtCore.QSize(390, 404))
        sign_in.setMaximumSize(QtCore.QSize(390, 404))
        self.centralwidget = QtWidgets.QWidget(sign_in)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei Light")
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.txt_username = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_username.setMinimumSize(QtCore.QSize(280, 50))
        self.txt_username.setMaximumSize(QtCore.QSize(385, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(18)
        self.txt_username.setFont(font)
        self.txt_username.setText("")
        self.txt_username.setObjectName("txt_username")
        self.verticalLayout.addWidget(self.txt_username)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.txt_password = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_password.setMinimumSize(QtCore.QSize(280, 50))
        self.txt_password.setMaximumSize(QtCore.QSize(385, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(18)
        self.txt_password.setFont(font)
        self.txt_password.setText("")
        self.txt_password.setObjectName("txt_password")
        self.verticalLayout_2.addWidget(self.txt_password)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(175, 25))
        self.label_6.setMaximumSize(QtCore.QSize(175, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setIndent(-1)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.create_account_link = QtWidgets.QLabel(self.centralwidget)
        self.create_account_link.setMinimumSize(QtCore.QSize(180, 25))
        self.create_account_link.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.create_account_link.setFont(font)
        self.create_account_link.setFocusPolicy(QtCore.Qt.NoFocus)
        self.create_account_link.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.create_account_link.setStyleSheet("")
        self.create_account_link.setLineWidth(1)
        self.create_account_link.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.create_account_link.setIndent(-2)
        self.create_account_link.setObjectName("create_account_link")
        self.gridLayout.addWidget(self.create_account_link, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.btn_signin = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei Light")
        font.setPointSize(15)
        self.btn_signin.setFont(font)
        self.btn_signin.setObjectName("btn_signin")
        self.verticalLayout_4.addWidget(self.btn_signin)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        sign_in.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(sign_in)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 390, 26))
        self.menubar.setObjectName("menubar")
        sign_in.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(sign_in)
        self.statusbar.setObjectName("statusbar")
        sign_in.setStatusBar(self.statusbar)

        self.retranslateUi(sign_in)
        QtCore.QMetaObject.connectSlotsByName(sign_in)

    def retranslateUi(self, sign_in):
        _translate = QtCore.QCoreApplication.translate
        sign_in.setWindowTitle(_translate("sign_in", "Sign İn"))
        self.label.setText(_translate("sign_in", "ToDo App"))
        self.label_2.setText(_translate("sign_in", "Sign In"))
        self.label_3.setText(_translate("sign_in", "Username"))
        self.label_5.setText(_translate("sign_in", "Passwordd"))
        self.label_6.setText(_translate("sign_in", "Don\'t have any accounts?"))
        self.create_account_link.setText(_translate("sign_in", "Create Now"))
        self.btn_signin.setText(_translate("sign_in", "Sign In"))

